version = 1

[[annotations]]
path = "DeeployTest/Tests/**"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "docs/_static/**"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.md"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.txt"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "**/*.patch"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = "*.json"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"

[[annotations]]
path = ".vscode/*.json"
SPDX-FileCopyrightText = "2023 ETH Zurich and University of Bologna"
SPDX-License-Identifier = "CC-BY-ND-4.0"