# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

---
name: Docker â€¢ Build Deeploy GAP9 Container

"on":
  workflow_dispatch:
    inputs:
      docker_image_deeploy:
        description: "Deeploy Image to use"
        required: false
        default: "ghcr.io/pulp-platform/deeploy:latest"

jobs:
  prepare:
    name: Fetch branch name or tag
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.generate_tag.outputs.docker_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up environment variables
        run: |
          echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "TAG_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
          echo "IS_TAG=${GITHUB_REF_TYPE}" >> $GITHUB_ENV

      - name: Set Docker tag
        id: generate_tag
        run: |
          if [[ "${{ env.IS_TAG }}" == "tag" ]]; then
            echo "docker_tag=${{ env.TAG_NAME }}" >> $GITHUB_OUTPUT
          else
            echo "docker_tag=${{ env.BRANCH_NAME }}" >> $GITHUB_OUTPUT
          fi

  build-deeploy-gap9:
    name: Build Deeploy GAP9 Image
    needs: [prepare]
    runs-on: ${{ matrix.runner }}
    outputs:
      digest-amd64: ${{ steps.digest.outputs.digest-amd64 }}
      digest-arm64: ${{ steps.digest.outputs.digest-arm64 }}
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v4

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: true
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - uses: docker/setup-buildx-action@v3

      - name: GHCR Log-in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Cache for Docker
        id: cache
        uses: actions/cache@v4
        with:
          path: var-ccache
          key: ${{ runner.os }}-${{ matrix.platform }}-build-cache-deeploy-gap9

      - name: Inject build-cache
        uses: reproducible-containers/buildkit-cache-dance@v3.1.0
        with:
          cache-map: |
            {
              "var-ccache": "/ccache"
            }
          skip-extraction: ${{ steps.cache.outputs.cache-hit }}

      - name: Lower Case Repository Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Build and push final deploy image
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/${{ matrix.platform }}
          context: .
          cache-from: type=gha
          cache-to: type=gha,mode=min
          file: Container/Dockerfile.gap9
          push: true
          build-args: |
            DEEPLOY_IMAGE=${{ github.event.inputs.docker_image_deeploy }}
          outputs: type=image,name=ghcr.io/${{ env.OWNER_LC }}/deeploy-gap9,annotation-index=true,name-canonical=true,push=true

      - name: Extract image digest
        id: digest
        run: echo "digest-${{ matrix.platform }}=${{ steps.build.outputs.digest }}" >> $GITHUB_OUTPUT

  merge-deeploy-gap9-images:
    name: Merge Deeploy GAP9 Images
    runs-on: ubuntu-latest
    needs: [prepare, build-deeploy-gap9]
    steps:
      - name: GHCR Log-in
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower Case Repository Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Merge Deeploy GAP9 Images
        uses: Noelware/docker-manifest-action@v1
        with:
          inputs: |
            ghcr.io/${{ env.OWNER_LC }}/deeploy-gap9@${{ needs.build-deeploy-gap9.outputs.digest-amd64 }},
            ghcr.io/${{ env.OWNER_LC }}/deeploy-gap9@${{ needs.build-deeploy-gap9.outputs.digest-arm64 }}
          tags: |
            ghcr.io/${{ env.OWNER_LC }}/deeploy-gap9:latest,
            ghcr.io/${{ env.OWNER_LC }}/deeploy-gap9:${{ needs.prepare.outputs.docker_tag }}
          push: true

      - name: Set package visibility to internal
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.packages.updatePackageVersionVisibility({
              package_type: 'container',
              package_name: 'deeploy-gap9',
              visibility: 'internal',
              org: context.repo.owner
            });
