# Copyright (C) 2025, ETH Zurich and University of Bologna.
# Licensed under the Apache License, Version 2.0, see LICENSE for details.
# SPDX-License-Identifier: Apache-2.0

---
name: _runner-softhier

"on":
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      docker-image:
        required: true
        type: string
      test-names:
        required: true
        type: string

jobs:
  test-runner-softhier:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        shell: bash
        run: pip install -e .
      - name: Run Test
        run: |
          testNames="${{ inputs.test-names }}"
          export SOFTHIER_INSTALL_DIR=/app/install/softhier
          cd DeeployTest
          echo "$testNames" | while IFS= read -r testName; do
            if [[ -n "$testName" ]]; then
              echo "Running test: $testName"
              python testRunner_softhier.py -t Tests/$testName --toolchain=GCC
            fi
          done
        shell: bash
