name: BuildDockerDeeploy

on:
  workflow_dispatch:

jobs:
  build-deeploy:
    name: Build Deploy Image
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ubuntu-22.04-arm
    steps:
      - uses: actions/checkout@v2

      - name: Free up disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          android: true
          dotnet: true
          haskell: true
          large-packages: true

      - uses: docker/setup-buildx-action@v1

      - name: GHCR Log-in
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lower Case Repository Name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push final deploy image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/${{ matrix.platform }}
          context: .
          file: Container/Dockerfile.deeploy
          push: true
          tags: ghcr.io/${{ env.OWNER_LC }}/deeploy:main
