# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

---
name: CI â€¢ Snitch

"on":
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:
    inputs:
      docker_image_deeploy:
        description: "Deeploy Image to use"
        required: false
        default: "ghcr.io/pulp-platform/deeploy:devel"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  select-env:
    uses: ./.github/workflows/_select-env.yml
    with:
      docker_image_deeploy: ${{ inputs.docker_image_deeploy }}

  snitch-kernels:
    needs: select-env
    uses: ./.github/workflows/_runner-snitch.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      test-names: |
        Kernels/FP32/Softmax/Regular
        Kernels/FP32/RMSNorm/single_fused_op
        Kernels/FP32/MatMul
        Kernels/FP32/Add/Regular
        Kernels/FP32/Hardswish
        Kernels/FP32/Div

        Kernels/Integer/Add/Large
        Kernels/Integer/Add/Regular

        Kernels/Integer/Softmax/Large
        Kernels/Integer/Softmax/Regular

        Kernels/Integer/MatMul/Regular

        Kernels/Integer/iNoNorm
        Kernels/Integer/GEMM/Regular_RQPerRow
        Kernels/Integer/Add/Regular_RQ
        Kernels/Integer/GEMM/TransB_RQ

        Models/microLlama/FP32/microLlama1
      num-cores: 9
      simulators: |
        gvsoc
