# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

---
name: CI â€¢ GAP9 (Tiled)

"on":
  push:
    branches:
      - "**"
    tags:
      - "v*.*.*"
  pull_request:
  workflow_dispatch:
    inputs:
      docker_image_deeploy:
        description: "Deeploy Image to use"
        required: false
        default: "ghcr.io/pulp-platform/deeploy-gap9:latest"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  select-env:
    uses: ./.github/workflows/_select-env.yml
    with:
      docker_image_deeploy: ${{ github.event.inputs.docker_image_deeploy || github.repository == 'pulp-platform/Deeploy' && 'ghcr.io/pulp-platform/deeploy-gap9:latest'}}

  gap9-kernels-tiled-singlebuffer-L2:
    needs: select-env
    uses: ./.github/workflows/_runner-gap9-tiled.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      pytest-markers: "gap9_tiled and kernels and singlebuffer and l2"

  gap9-kernels-tiled-doublebuffer-L2:
    needs: select-env
    uses: ./.github/workflows/_runner-gap9-tiled.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      pytest-markers: "gap9_tiled and kernels and doublebuffer and l2"

  gap9-models-tiled-singlebuffer-L2:
    needs: select-env
    uses: ./.github/workflows/_runner-gap9-tiled.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      pytest-markers: "gap9_tiled and models and singlebuffer and l2"

  gap9-models-tiled-doublebuffer-L2:
    needs: select-env
    uses: ./.github/workflows/_runner-gap9-tiled.yml
    with:
      runner: ${{ needs.select-env.outputs.runner }}
      docker-image: ${{ needs.select-env.outputs.image }}
      pytest-markers: "gap9_tiled and models and doublebuffer and l2"
