# SPDX-FileCopyrightText: 2025 ETH Zurich and University of Bologna
#
# SPDX-License-Identifier: Apache-2.0

---
name: Infrastructure â€¢ Generate CCache

"on":
  workflow_dispatch:
    inputs:
      docker_image_deeploy:
        description: "Deeploy Image to use"
        required: false
        default: "ghcr.io/pulp-platform/deeploy:devel"
  schedule:
    # Runs the workflow on the default branch every day at 1AM CET to keep the cache fresh
    - cron: "0 1 * * *"

jobs:
  generate-ccache:
    runs-on: ubuntu-latest
    container:
      image: ${{ github.event.inputs.docker_image_deeploy || 'ghcr.io/pulp-platform/deeploy:devel' }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        shell: bash
        run: pip install -e .

      # python testRunner_generic.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_mempool.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_cortexm.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_snitch.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_tiled_snitch.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_siracusa.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_tiled_siracusa.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_tiled_siracusa_w_neureka.py -t ./Tests/Kernels/Integer/Add/Regular
      # python testRunner_chimera.py -t ./Tests/Kernels/Integer/Add/Regular

      - name: Generate CCache
        run: |
          cd DeeployTest
          mkdir -p /app/.ccache
          export CCACHE_DIR=/app/.ccache
          pytest 'test_platforms.py::test_generic_kernels[Adder]' --skipsim
          pytest 'test_platforms.py::test_mempool_kernels[Adder]' --skipsim
          pytest 'test_platforms.py::test_cortexm_kernels[Adder]' --skipsim
          pytest 'test_platforms.py::test_snitch_kernels[Adder]' --skipsim
          pytest 'test_platforms.py::test_snitch_tiled_kernels[Adder-128000-L2]' --skipsim
          pytest 'test_platforms.py::test_siracusa_kernels[Adder]' --skipsim
          pytest 'test_platforms.py::test_siracusa_tiled_kernels_singlebuffer_l2[Adder-64000-L2-singlebuffer]' --skipsim
          pytest 'test_platforms.py::test_siracusa_neureka_tiled_kernels_l2_singlebuffer[testRequantizedLinear-16000-L2-singlebuffer]' --skipsim
          pytest 'test_platforms.py::test_chimera_kernels[Adder]' --skipsim

      - name: Clean and Upload CCache
        uses: actions/cache@v4
        with:
          path: /app/.ccache
          key: ccache-ci
            