name: TestRunnerCortexM

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      test-names:
        required: true
        type: string

jobs:
  test-runner-cortexm:
    runs-on: self-hosted
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        run: pip install -e .
      - name: Run Test
        run: |
          testNames="${{ inputs.test-names }}"
          cd DeeployTest
          echo "$testNames" | while IFS= read -r testName; do
            if [[ -n "$testName" ]]; then
              echo "Running test: $testName"
              python testRunner_cortexm.py -t Tests/$testName
            fi
          done
        shell: bash
          