name: TestRunnerSnitch

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      docker-image:
        required: true
        type: string
      test-names:
        required: true
        type: string
      num-cores:
        required: true
        type: number
      simulators:
        required: true
        type: string      

jobs:
  test-runner-snitch:
    runs-on: ${{ inputs.runner }}
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        run: pip install -e .
      - name: Cache ccache
        uses: actions/cache/restore@v4
        with:
          path: /app/.ccache
          key: ccache-ci
      - name: Run Test
        run: |
          testNames="${{ inputs.test-names }}"
          simulators="${{inputs.simulators}}"
          cd DeeployTest
          mkdir -p /app/.ccache
          export CCACHE_DIR=/app/.ccache
          echo "$simulators" | while IFS= read -r simulator; do
            if [[ -n "$simulator" ]]; then
              echo "$testNames" | while IFS= read -r testName; do
                if [[ -n "$testName" ]]; then
                  echo "Running test $testName using $simulator"
                  python testRunner_snitch.py -t Tests/$testName --simulator=$simulator --cores=${{ inputs.num-cores }}
                fi
              done
            fi
          done
        shell: bash