name: TestRunnerSoftHier

on:
  workflow_call:
    inputs:
      docker-image:
        required: true
        type: string
      test-names:
        required: true
        type: string

jobs:
  test-runner-softhier:
    runs-on: ubuntu-22.04
    container:
      image: ${{ inputs.docker-image }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        run: pip install -e .
      - name: Run Test
        run: |
          testNames="${{ inputs.test-names }}"
          export SOFTHIER_INSTALL_DIR=/app/install/softhier
          cd ${SOFTHIER_INSTALL_DIR} 
          source sourceme_deeploy.sh
          cd /__w/Deeploy/Deeploy
          cd DeeployTest
          echo "$testNames" | while IFS= read -r testName; do
            if [[ -n "$testName" ]]; then
              echo "Running test: $testName"
              python testRunner_softhier.py -t Tests/$testName --toolchain=GCC
            fi
          done
        shell: bash
        