name: TestRunnerTiledSiracusaWithNeureka

on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      num-cores:
        required: false
        default: 8
        type: number
      L1:
        required: false
        default: "[64000]"
        type: string
      default-memory-level:
        required: false
        default: "L2"
        type: string
      double-buffer:
        required: false
        default: false
        type: boolean
      neureka-wmem:
        required: false
        default: false
        type: boolean

jobs:

  test-runner-siracusa-neureka-tiled:
    strategy:
      fail-fast: false
      matrix:
        L1: ${{ fromJSON(inputs.L1) }}
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/tahaelbayad/deeploy:main
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build Deeploy
        run: pip install -e .
      - name: Cache ccache
        id: ccache-cache-neureka
        uses: actions/cache@v4
        with:
          path: /app/.ccache
          key: ${{ runner.os }}-ccache-neureka
      - name: Run Test
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 5
          max_attempts: 3
          retry_on: timeout
          command: |
            cd DeeployTest
            mkdir -p /app/.ccache
            export CCACHE_DIR=/app/.ccache
            source /app/install/pulp-sdk/configs/siracusa.sh
            python testRunner_tiled_siracusa_w_neureka.py -t Tests/${{ inputs.test-name }} --cores=${{ inputs.num-cores }} --l1 ${{ matrix.L1 }} --defaultMemLevel=${{ inputs.default-memory-level }} ${{ inputs.double-buffer && '--doublebuffer' || '' }} ${{ inputs.neureka-wmem && '--neureka-wmem' || '' }}
          shell: bash
        